# Generated by Django 2.1.1 on 2018-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(blank=True, db_column='CG_UM_ALTER_EMPLID', max_length=10, primary_key=True, serialize=False),
        ),
    ]
